CREATE FOREIGN TABLE IF NOT EXISTS SA_CONSUMER_SEGMENT.EXT_CONSUMER_SEGMENT 
					(
					order_srcid varchar(255) ,
					order_priority varchar(255),
					order_date varchar(255),
					ship_date varchar(255),
					shipment_srcid varchar(255),
					ship_mode varchar(255),
					shipment_type varchar(255),
					customer_srcid varchar(255),
					customer_name varchar(255),
					customer_dob varchar(255),
					customer_full_age varchar(255),
					customer_gender varchar(255),
					customer_email varchar(255),
					customer_phone varchar(255),
					customer_address_id varchar(255),
					customer_address varchar(255),
					customer_city_id varchar(255),
					customer_city varchar(255),
					customer_country_id varchar(255),
					customer_country varchar(255),
					customer_region_id varchar(255),
					customer_region varchar(255),
					supplier_srcid varchar(255),
					supplier_name varchar(255),
					manager_srcid varchar(255),
					supplier_manager_name varchar(255),
					supplier_manager_phone varchar(255),
					supplier_manager_email varchar(255),
					supplier_address_id varchar(255),
					supplier_address varchar(255),
					supplier_city_id varchar(255),
					supplier_city varchar(255),
					supplier_country_id varchar(255),
					supplier_country varchar(255),
					supplier_region_id varchar(255),
					supplier_region varchar(255),
					supplier_status varchar(255),
					market_srcid varchar(255),
					market_desc varchar(255),
					market_address_id varchar(255),
					market_address varchar(255),
					market_city_id varchar(255),
					market_city varchar(255),
					market_country_id varchar(255),
					market_country varchar(255),
					market_region_id varchar(255),
					market_region varchar(255),
					employee_srcid varchar(255),
					employee_name varchar(255),
					employee_surname varchar(255),
					employee_full_name varchar(255),
					employee_dob varchar(255),
					employee_email varchar(255),
					employee_phone varchar(255),
					employee_position varchar(255),
					product_srcid varchar(255),
					product_desc varchar(255),
					product_category_id varchar(255),
					product_category_desc varchar(255),
					product_group_id varchar(255),
					product_group_desc varchar(255),
					product_price  varchar(255),
					sales_amount varchar(255),
					quantity varchar(255),
					discount varchar(255),
					profit varchar(255),
					shipping_cost varchar(255),
					product_status varchar(255),
					loyal_program_srcid varchar(255),
					loyal_program_desc varchar(255),
					loyal_discount varchar(255)
					) 
		SERVER pglog
		OPTIONS (format 'csv', HEADER 'true', filename 'C:\Users\alexe\OneDrive\Documents\Epam_lab\Epam\_DWH\dataset\5%\CONSUMER_SEGMENT_TOTAL_5.csv', 
		delimiter ',', null '', ENCODING 'latin1') ;
COMMIT; -- DROP FOREIGN TABLE SA_CONSUMER_SEGMENT.EXT_CONSUMER_SEGMENT;