CREATE OR REPLACE FUNCTION BL_CL.create_partition (FORDATE DATE) 
RETURNS VOID
AS $$
	DECLARE MONTHSTART DATE := DATE_TRUNC('MONTH', FORDATE);
    DECLARE MONTHENDEXCLUSIVE DATE := MONTHSTART + INTERVAL '1 MONTH';
    DECLARE TABLENAME TEXT := 'BL_DM.FCT_SALES_PARTITION_' || TO_CHAR(MONTHSTART, 'YYYY_MM');
BEGIN
    IF TO_REGCLASS(TABLENAME) IS NULL THEN
        EXECUTE FORMAT('CREATE TABLE IF NOT EXISTS
		 %I PARTITION OF BL_DM.FCT_SALES FOR VALUES FROM (%L) TO (%L)', TABLENAME, MONTHSTART, MONTHENDEXCLUSIVE);
    END IF;
END;
$$ LANGUAGE PLPGSQL;


DO
$$
DECLARE REC DATE;
BEGIN

    FOR REC IN SELECT GENERATE_SERIES('2019-01-01'::DATE,'2028-12-31'::DATE,'1 MONTH'::INTERVAL)::DATE LOOP
        PERFORM BL_CL.create_partition(REC::DATE);  
    END LOOP;
END
$$;